trigger:
  branches:
    include:
    - master
    - dev/*
  paths:
    exclude:
    - README.md

variables:
  poolName: HomeServers
  imageName: 'registry.gitlab.com/ricardosantos9521/github/reactproject:$(Build.BuildNumber)'
  dockerRegistryEndpoint: 'gitlab registry'

stages:
#build stage
- stage: Build
  jobs:
  - job: BuildJob
    pool: $(poolName)
    steps:
    - task: Docker@1
      displayName: 'Build an image'
      inputs:
        containerregistrytype: 'Container Registry'
        command: 'Build an image'
        imageName: $(imageName)
        dockerFile: Dockerfile
        dockerRegistryEndpoint: $(dockerRegistryEndpoint)
    - task: Docker@1
      displayName: 'Push an image'
      inputs:
        containerregistrytype: 'Container Registry'
        command: 'Push an image'
        imageName: $(imageName)
        dockerFile: Dockerfile
        dockerRegistryEndpoint: $(dockerRegistryEndpoint)
    - task: CopyFiles@1
      displayName: copy kubernetes yaml
      inputs: 
        contents: "deployment.yaml"
        targetFolder: $(Build.ArtifactStagingDirectory)
    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: drop

#deploy stage
- stage: Deploy
  dependsOn: Build
  condition: |
    and(
      eq(variables['Build.SourceBranch'], 'master'),
      and(
        ne(variables['Build.Reason'], 'PullRequest'), 
        eq(startsWith(variables['Build.SourceBranch'], 'dev/'), 'false')
      )
    )
  jobs:
  - job: DeployJob
    pool: $(poolName)
    steps:
    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'current'
        artifactName: 'drop'
        downloadPath: '$(System.DefaultWorkingDirectory)'
    - task: kasunkodagoda.regex-match-replace.regex-match-replace.RegExMatchReplace@2
      displayName: 'RegEx Match & Replace'
      inputs:
        PathToFile: '$(System.DefaultWorkingDirectory)/drop/deployment.yaml'
        RegEx: BUILDNUMBER
        ValueToReplace: '$(Build.BuildNumber)'
    - task: Kubernetes@1
      inputs:
        connectionType: 'None'
        command: 'apply'
        useConfigurationFile: true
        configuration: '$(System.DefaultWorkingDirectory)/drop/deployment.yaml'
        secretType: 'dockerRegistry'
        containerRegistryType: 'Container Registry'
        dockerRegistryEndpoint: $(dockerRegistryEndpoint)
        secretName: 'dockerregistrysecret'
        checkLatest: true