apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-frontend-dpl
  namespace: project
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 2
  selector:
    matchLabels:
      app: project-frontend
  template:
    metadata:
      labels:
        app: project-frontend
    spec:
      containers:
        - name: project-frontend
          image: "registry.gitlab.com/ricardosantos9521/project/frontend:BUILDNUMBER"
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "100Mi"
              cpu: "150m"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
      imagePullSecrets:
        - name: gitlabdockersecret
---
apiVersion: v1
kind: Service
metadata:
  name: project-frontend-svc
  namespace: project
spec:
  selector:
    app: project-frontend
  ports:
    - port: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: project-frontend-ing
  namespace: project
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/add-base-url: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - ricspt.ddns.net
      secretName: tlscert
  rules:
    - host: ricspt.ddns.net
      http:
        paths:
          - path: /project/frontend/(.*)
            backend:
              serviceName: project-frontend-svc
              servicePort: 80
