apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactproject-dpl
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 2
  selector:
    matchLabels:
      app: reactproject
  template:
    metadata:
       labels:
         app: reactproject
    spec:
      containers:
      - name: reactproject
        image: "registry.gitlab.com/ricardosantos9521/github/reactproject:BUILDNUMBER"
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "100Mi"
            cpu: "150m"
        readinessProbe:
          httpGet:
             path: /
             port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
      imagePullSecrets:
        - name: secretteamrics
---
apiVersion: v1
kind: Service
metadata:
  name: reactproject-svc
spec:
  selector:
    app: reactproject
  ports:
  - port: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: reactproject-ing
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/add-base-url: "true"
    # nginx.ingress.kubernetes.io/ingress.allow-http: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - http:
      paths:
      - path: /reactproject(.*)
        backend:
          serviceName: reactproject-svc
          servicePort: 80